import Header from "@/components/Header";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` bg-dark-900 text-light-50 ${roboto.className}`}>
        <main className=" flex flex-col justify-center w-full items-center">
        <Header/>
          {children}
          <div className="h-screen back-image  w-full absolute inset-0 "></div>
        </main>
      </body>
    </html>
  );
}
